Download csv and json
TPiechocki/ServerRoomMonitoringApp pull request #14
Opened 2021-12-01 22:58 UTC by RozaliaSolecka

2021-12-02 11:55 UTC, TPiechocki requested changes

2021-12-02 11:55 UTC, TPiechocki commented on ServerRoomMonitoring.Web/Controllers/SensorMessagesController.cs
> +        private string GenerateCSVString()
Ta metoda nie powinna być w kontrolerze.

2021-12-02 11:55 UTC, TPiechocki commented on ServerRoomMonitoring.Web/Startup.cs
> +            services.AddSingleton<ISensorRepository, MockSensorRepository>();
Repozytoria raczej powinny być `Scoped`. Wtedy każdy użytkownik na stronie ma swoje repozytorium, więc np. każdy użytkownik może czytać równolegle, jeśli repozytorium jest asynchroniczne (generalnie zawsze repozytoria mogą być async, bo np. oczekiwanie na przetwarzanie przez bazę danych może być z awaitem).

2021-12-05 15:46 UTC, RozaliaSolecka commented on ServerRoomMonitoring.Web/Controllers/SensorMessagesController.cs
> +        private string GenerateCSVString()
Gdzie powinna być?

2021-12-05 15:48 UTC, TPiechocki commented on ServerRoomMonitoring.Web/Controllers/SensorMessagesController.cs
> +        private string GenerateCSVString()
Raczej kontroler powinien wołać jakiś serwis biznesowy. Chociażby `CSVGenerator`.

2021-12-07 15:47 UTC, TPiechocki approved these changes

2021-12-07 15:47 UTC, merged