Generator
TPiechocki/ServerRoomMonitoringApp pull request #9
Opened 2021-11-10 19:36 UTC by Magdalena-N

2021-11-10 20:00 UTC, RozaliaSolecka approved these changes
Looks nice

2021-11-11 14:15 UTC, TPiechocki requested changes

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Conditions/IStatus.cs
> +        public bool Stopped { get; set; }
Na interfejsach pola i metody nie powinny mieć opisanej widoczności (w sensie bool nie musi już mieć public). Zakres widoczności pól i metod, jest na podstawie widoczności całego interfejsu.

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Messaging/SensorQueue.cs
> +            _queueName = rabbitMqOptions.Value.QueueName;
Czyściej będzie chyba nie zapisywać tych 4 wartości z configu, tylko przekazać całą instancję configu do metody CreateConnection i po prostu tam odczytać to co potrzebne.

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Messaging/SensorQueue.cs
> +            if (ConnectionExists())
Dla zabezpieczenia dodałbym else z logowaniem errora, że połączenia nie ma.

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Messaging/SensorQueue.cs
> +                    Console.WriteLine("{0} has been sent to the queue.", json);
Lepiej przez loggera to wrzucać, żeby mieć chociażby timestamp oraz klasę, która to zalogowała. Wstrzykiwalny interfejs `ILogger<nazwa_klasy>`. Komentarz jak skonfigurować w Program.cs dorzuciłem.

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Messaging/SensorQueue.cs
> +                    Console.WriteLine("{0} has been sent to the queue.", json);
To samo dotyczy wszystkich Console.WriteLine oczywiście.

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Models/Sensor.cs
> +    // obiekt dto
polski komentarz :P

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Services/GeneratorBackgroundService.cs
> +                foreach (var sensor in _serverRoom.Sensors)
Przy takiej sekwencyjnej pętli, czasy opóźnień nie będą między wiadomościami dla jednego sensora. Wyśle pierwszy sensor, oczekiwanie pierwszego sensora, wyśle drugi sensor, oczekiwanie na drugi sensor itd. Zupełnie nie jest to równoległe.
Zamiast tego ten serwis powinien uruchomić każdy sensor w osobnym wątku np. `Task.Run` i każdy sensor powinien niezależnie od siebie generować wiadomości w takiej pętli.

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Models/IServerRoom.cs
> +        public  List<Sensor> Sensors { get; set; }
Chyba setter nie jest potrzebny na zewnątrz. No i lepiej w interfejsach korzystać z interfejsów. Albo `IEnumerable`, jeśli sensory potrzebne tylko do pętli foreach, albo `ICollection`, jeśli jest potrzebne coś więcej,

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Models/Sensor.cs
> +            _config = configuration.GetSection(id.ToString()).Get<SensorConfig>();
Sensor powinien już dostać config tylko dla siebie, a nie kolekcję dla wszystkiego.

2021-11-11 14:15 UTC, TPiechocki commented on ServerRoomMonitoring.Generator/Program.cs
> +                .ConfigureWebHostDefaults(webBuilder =>
Skonfiguruj logger tak samo jak w projekcie apki webowej. Potrzebny również będzie plik log4net.config.

2021-11-30 20:52 UTC, TPiechocki approved these changes

2021-11-30 21:14 UTC, merged